### ISSUE TITLE
Swedish language pack for Flarum

### ISSUE THREAD

**Issue by FullThrottle83** [Free-Flarum/freeflarum.com#381]
https://github.com/flarum-lang/swedish

## Why should this extension be installed?

Since the popularity amongs Swedes is increasing.

Thank you in advance!

**Comment by FullThrottle83** [comment]
Thank you very much for implementing it in todays update.
Unfortunatly it doesn't work.

I've disabled english, so Swedish is the only language.
Also cleared cache. Still only english :/

**Comment by CWKevo** [comment]
The thing is, I actually didn't include it directly (I would announce it here if I would). It was probably a result of me rolling back skeleton forum, which brought back all the recently removed extensions.

I will keep this one though, as I would re-add it at some point in time anyways. I guess I can close this then.

**Comment by FullThrottle83** [comment]
Has Swedish and a bunch of other languages been removed?
It's gone on my forum, and isn't to be found amongst extensions.

Thank you for your hard work!

**Comment by CWKevo** [comment]
Yes, sorry. I forgot that I've rolled back our composer file during the upgrade to Flarum 1.4.0. I've re-added Arabic, Passport and Swedish, as you and others have requested.

As for other languages, they have been removed because not many forums use them (https://discuss.flarum.org/d/7585/3828) - feel free to open/reply to an issue to have them re-added!
